### ISSUE TITLE
Fit long mutation names in popup

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/mutation-testing-elements#41]
Mutation names get hard to read when they are long. 

Example:
![image](https://user-images.githubusercontent.com/14224500/58336735-9558a000-7e44-11e9-85d9-c09e6f8ae55a.png)

Maybe we could fit the popup to the content? Or we could make them larger by default?

**Comment by nicojs** [comment]
Why is the mutator name so long? I would suggest renaming it to [unary operator](https://github.com/stryker-mutator/stryker-handbook/blob/master/mutator-types.md#unary-operator) for this mutator, right?

For the reasons explained below, I want to keep a fixed width. We could make it larger by default, but that looks uglier for smaller names. I would suggest keeping the mutator names short and sweet. Additional info could also be added to [the description field when it is supported](https://github.com/stryker-mutator/mutation-testing-elements/pull/37).

More background on the design choice:

We're rolling our own popup implementation based on [w3schools example](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_popup). It has the limitation of having a fixed width title, but the benefit of smaller bundle size and is simpler to maintain. I tried to integrate the more expensive [popper.js](https://github.com/FezVrasta/popper.js) at first but ran into all sorts of problems as it not "web-components minded" yet. If anyone wants to try dynamically sizing the popup with the content, be my guest. 

Note: I think it's just a matter of time before a pure web-components implementation of bootstrap is a thing, so I'm willing to wait for that (and probably be disappointed with a fixed popup width implementation 🙈 ). 

N.B. Calculating the width of the text and solving it with pure JS is also not easy since the font isn't monospaced.

**Comment by hugo-vrijswijk** [comment]
I agree with @nicojs. We defined the mutation categories to be more uniform. So we should stick to it not just in class names, but also in communication to the user

**Comment by nicojs** [comment]
@richardwerkman can we close this issue? We've recently added [a description field to a mutant](https://github.com/stryker-mutator/mutation-testing-elements/pull/37), allowing for longer explanations there.
